name: PlayerLog
main: cn.lanink.playerlog.PlayerLog
version: "1.0.2-SNAPSHOT"
api:
  - 1.0.0
load: POSTWORLD
author: LT_Name
depend:
  - "EasyMySQL"

permissions:
  PlayerLog.Command.DelBlockLog:
    description: "PlayerLog 删除方块记录命令权限"
    default: op
  PlayerLog.Command.Query:
    description: "PlayerLog 查询命令权限"
    default: op